// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCFuLJDWelCHpCdJYENt7nBswj7G7RvqyY",
  authDomain: "rizzume-63a35.firebaseapp.com",
  projectId: "rizzume-63a35",
  storageBucket: "rizzume-63a35.firebasestorage.app",
  messagingSenderId: "750400549659",
  appId: "1:750400549659:web:761413168df712a3d9d9be",
  measurementId: "G-MLQBG7QBQH"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDapNCX7THlWqeRkr5-32Hsbny_xUcpDUo',
    appId: '1:750400549659:android:921cf31b1bca51ded9d9be',
    messagingSenderId: '750400549659',
    projectId: 'rizzume-63a35',
    storageBucket: 'rizzume-63a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkrjpyyib73qHfVs2FknEEwx3tiZsqu4',
    appId: '1:750400549659:ios:100686e29bb20ea7d9d9be',
    messagingSenderId: '750400549659',
    projectId: 'rizzume-63a35',
    storageBucket: 'rizzume-63a35.appspot.com',
    iosBundleId: 'com.example.rizzume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'rizzume-63a35',
    storageBucket: 'rizzume-63a35.appspot.com',
    iosBundleId: 'com.example.rizzume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
  apiKey: "AIzaSyCFuLJDWelCHpCdJYENt7nBswj7G7RvqyY",
  authDomain: "rizzume-63a35.firebaseapp.com",
  projectId: "rizzume-63a35",
  storageBucket: "rizzume-63a35.firebasestorage.app",
  messagingSenderId: "750400549659",
  appId: "1:750400549659:web:fda3c0f9adc3a81cd9d9be",
  measurementId: "G-EMFV5D51LM"
  );
}
